### ISSUE TITLE
downloads some font files when we try to search webID uri

### ISSUE THREAD

**Issue by safesurfer** [joshuef/eat#5]
downloads following font files when we try to search webID uri
* font_148784_v4ggb6wrjmkotj4i.ttf
* font_148784_v4ggb6wrjmkotj4i.woff

**Comment by bochaco** [comment]
@safesurfer , do you remember if the webid entered exists or not, if it exists which was the content of it? we'd need more info of how you got to reproduce this. Also, are you running from localhost?

**Comment by safesurfer** [comment]
@bochaco , No, I'm not running from localhost. This is not found when we run from localhost and I checked it. I uploaded the social app using WHM. When we click search button, even though nothing is given as input, it downloads two files. but only for the first time, if you click next time it says `webid entered not found`

**Comment by safesurfer** [comment]
and what ever `webid uri` I enter whether it exists or not, it throws an error saying `webid entered not found`

**Comment by lionel1704** [comment]
I just ran into the same issue.
- I'm using web hosting manager to upload the built social app and web ID manager
- When looking for a web ID that does not exist, a pop-up on the top right shows web ID not found.
- There are two http requests that go out resulting in the downloading of the font files. There are the URLS. They open in my firefox and the download dialog box opens up
https://at.alicdn.com/t/font_148784_v4ggb6wrjmkotj4i.woff
https://at.alicdn.com/t/font_148784_v4ggb6wrjmkotj4i.ttf
- This happens only the first time after every refresh. From the second time onwards only the pop-up comes up.

**Comment by bochaco** [comment]
Thanks @lionel1704 , I think I know what's happening, this is a WIP feature to show an alert but we still need to figure out how to import the fonts so they can be uploaded onto the SAFE network as well along with the site's files. If you try this with the code from the repo you won't be able to reproduce it, this got in by mistake in the version we manually packaged and shared.

**Comment by safesurfer** [comment]
@bochaco , The same thing happens, when we try to upload an image other than *.jpg, followed by the message `You can only upload JPG file!`, while creating WebID.

**Comment by bochaco** [comment]
Thanks @safesurfer , whenever we find the solution we'll be able to apply it to both apps.

**Comment by joshuef** [comment]
sorted via a peruse icon serving hack until `.lessrc` is available for parcel or we go webpack. Closing for now.
