### ISSUE TITLE
Switching accounts doesn't request authorisation

### ISSUE THREAD

**Issue by lionel1704** [joshuef/eat#7]
- Create multiple web IDs.
- Login to Not Twitter through any of them. 
- Authorisation is requested and once  accepted it logs in.
- Switch accounts through the profile icon. The account in the Not Twitter app changes without any authentication.

Seems as though, once Not Twitter is authorised it's capable of switching the logged-in accounts without additional authorisation.

**Comment by bochaco** [comment]
This is as designed @lionel1704 , this is the whole idea of using webids so you don't have to authorise or log-in in a traditional way but just switch your profiles and allow apps to use it.

**Comment by lionel1704** [comment]
Thanks @bochaco! That clears it up :)
